- [十一、几个关键问题](#十一几个关键问题)
  - [11.1 如何修改 promise 对象状态](#111-如何修改-promise-对象状态)
  - [11.2 指定多个回调执行情况](#112-指定多个回调执行情况)
  - [11.3 指定回调与改变状态先后顺序问题](#113-指定回调与改变状态先后顺序问题)
  - [11.4 promise.then()返回的新promise的结果状态由什么决定？](#114-promisethen返回的新promise的结果状态由什么决定)
  - [11.5 promise如何串联多个操作任务?](#115-promise如何串联多个操作任务)
  - [11.6 promise的异常穿透](#116-promise的异常穿透)
  - [11.7 中断promise链](#117-中断promise链)

### 十一、几个关键问题

#### 11.1 如何修改 promise 对象状态

~~~js
<script>
    //如何修改 promise 对象状态
    let p = new Promise((resolve, reject) => {
        //1. resolve
        // resolve('success');
        //2. reject
        // reject('error');
        //3. 抛出错误 异常
        // throw '出问题啦! 你说出这样的话  你没有良心!!';
        // 状态的改变只有一次 
        resolve('ok');
        reject('error');
    });
	console.log(p);
</script>
~~~

#### 11.2 指定多个回调执行情况

问题：一个promise指定多个成功/失败回调函数，都会调用吗？

答：会，但是前提是当promise对象的状态改变(fulfilled/rejected)时才会调用

~~~js
<script>
        let p = new Promise((resolve, reject) => {
            //promise对象是可以多次调用then方法完成多个成功/失败回调函数
            //但是使用的前提是这个promise对象的状态必须要么是fulfilled或者是rejected
            //不能是pending
            resolve('OK');
        });	
		
        //第一次指定回调
        p.then(value => {
            console.log(value);
        }, reason => {
            console.error(reason);
        });

        p.then(value => {
            alert(value);
        }, reason => {
            alert(reason);
        })
</script>
~~~

#### 11.3 指定回调与改变状态先后顺序问题

改变promise状态和指定回调函数执行谁先谁后？

- 都有可能，正常情况下是先指定回调再改变状态，但也可以先改变状态在指定回调

  ~~~js
  //若执行器函数中是异步任务, 则先指定回调, 然后再改变状态  更为常见
  //若执行器函数中是同步任务, 则先改变状态, 然后再指定回调
  let p = new Promise((resolve, reject) => {
      //同步任务
      //resolve('ok');
      //异步任务
      setTimeout(() => {
          resolve('ok');
      }, 1000);
  });
  ~~~

- 如何先改状态再指定回调？

  - 在执行器中直接调用resolve()/reject()

  ~~~js
  let p = new Promise((resolve, reject) => {
  	//resolve('ok');
  	reject('error');
  });
  ~~~

  - 延迟更长时间才调用then()

  ~~~js
  const p = new Promise((resolve, reject) => {
      setTimeout(() => {
          resolve('ok');
      }, 1000)
  
  })
  //then方法使用定时器延迟更久的时间
  setTimeout(() => {
      p.then(value => {
          console.log(value);
      }, reason => {
          console.log(reason);
      })
  
  }, 3000)
  ~~~

- 什么时候才能得到数据？

  - 如果是先指定的回调，那当状态发生改变时，回调函数就会调用，得到数据
  - 如果先改变的状态，那当指定回调时，回调函数就会调用，得到数据

#### 11.4 promise.then()返回的新promise的结果状态由什么决定？

- 简单表达：由then指定的回调函数执行的结果决定
- 详细表达：
  - 如果抛出异常：新promise对象状态变成rejected，reason为抛出的异常
  - 如果返回的是是非promise的任意值，新promise对象状态变成fulfilled，value为返回的值
  - 如果返回的是另一个新的promise对象，此promise的结果就会称为新promise的结果

~~~js
const p = new Promise((resolve, reject) => {
    resolve('ok');
})
let result = p.then(value => {
    //return value;
    return new Promise((resolve, reject) => {
        resolve('okk');
    })
}, reason => {
    console.log(reason);
})
console.log(result);
~~~

#### 11.5 promise如何串联多个操作任务?

- promise的then()返回一个新的promise对象，可以写成then()方法的链式调用
- 通过then()的链式调用串联多个同步/异步任务

~~~js
<script>
    new Promise((resolve, reject) => {
            console.log(111);
            reject();
    }).then(value => {
            console.log(222);
    }).then(value=> {
            console.log(value);
    }).then(value => {
            console.log(value)
    }, reason => {
            console.error(reason);
    });
</script>
~~~

#### 11.6 promise的异常穿透

- 当使用promise的then链式调用时, 可以在最后指定失败的回调,
- 前面任何操作出了异常, 都会传到最后失败的回调中处理

~~~js
new Promise((resolve, reject) => {
    console.log(111);
    reject('error');
}).then(value => {
    console.log(222);
}).then(value => {
    console.log(value);
}).then(value => {
    console.log(value)
}).catch(reason => {
    console.log(reason);
})
~~~

#### 11.7 中断promise链

- 当使用promise的then链式调用时, 在中间中断, 不再调用后面的回调函数
- 办法: 在回调函数中返回一个pending状态的promise对象

~~~js
new Promise((resolve, reject) => {
    console.log(111);
    resolve('ok');
}).then(value => {
    console.log(222);
}).then(value => {
    console.log(value);
    return new Promise(() => { })
}).then(value => {
    console.log(value)
}, reason => {
    console.error(reason);
});
~~~
